### ISSUE TITLE
connections not releasing properly

### ISSUE THREAD

**Issue by fryeguy63** [pekim/tedious-connection-pool#22]
I took over a project using this module to manage MSSQL connections. Many of the API endpoints have multiple queries. One query gets a list of IDs. Each ID is then used in an additional query. The code uses a simple for loop to manage the queries.

I have found that the maximum number of queries that can be run inside the loop is equal to the MIN connections configuration setting. So if MIN is 10, the first ten queries run fine inside of the loop. All the other queries return the same results as the 10th query. If I adjust the MIN value the number of successful queries changes accordingly. The MAX value appears to have no effect. Setting the connection pool MIN to 0 I get one good query and the rest fail in this context.

Connection.release() gets called but it appears that connections are released after additional query attempts are made and it looks like no connections are available.

Here is a chunk of the code:
```
// GET All IDs to lookup stuff
router.get('/:Id/list_of_stuff',
    passport.authenticate('basic', {session: false}),
    function(req, res){
        var data = [];
        DB.pool.acquire(function(err, connection){
            if (err)
                console.log(err);
            // Get All Vendors
            var getAllIds = new Request('' +
                'USE db_name ' +
                'SELECT StuffID, Name ' +
                'FROM dbo.StuffStuffNames ' +
                'WHERE ID = @stuffId ',
                function(err, stuffRowCount, stuff){
                    // Failure Conditions
                    if (err){
                        console.error(err);
                        return;
                    }
                    connection.release();
                    var rowCounter = 1;
                    for (var i = 0; i < stuffRowCount - 1; i++){
                        console.log('stuffID -- ', stuff[i][0].value);
                        // Every Iteration Gets It's Own Connection
                        // Grab all Employee's Tied to a stuff record
                        DB.pool.acquire(function(err, connection){
                            if (err) {
                                console.log(err);
                            }
                            var currentIteration = i;
                            var getStuffCount = new Request('' +
                                'USE db_name ' +
                                'SELECT EmployeeID, Field1, Field2, Field3 ' +
                                'FROM dbo.StuffEmployeeAssignment ' +
                                'WHERE StuffID = @stuffId',
                                function(err, rowCount, rows){
                                    if (err){
                                        console.error('ERROR -- ', err);
                                        return;
                                    }

                                    // .release() appears to do nothing or to do it to late to be effective
                                    connection.release();

                                    // create some variables to store some data

                                    // loop over the query results and increment some counters

                                    // Return on Last Iteration
                                    // This counter and all the rest with the -1 are strange
                                    // and I think may be incorrect. seem to be off by one
                                    if (rowCounter === (stuffRowCount - 1)){
                                        res.json([{success: true}, data]);
                                    }else{
                                        rowCounter++;
                                    }
                                }
                            );
                            // stuff comes from first query and is used in the query inside of this request
                            getStuffCount.addParameter('stuffId', TYPES.UniqueIdentifier, stuff[i][0].value);
                            connection.execSql(getStuffCount);
                        });
                    }
                }
            );
            getAllIDs.addParameter('stuffId', TYPES.UniqueIdentifier, req.params.Id);
            connection.execSql(getAllIDs);
        });
    });
```

The product we are building is for a major contract and the previous developer missed multiple deadlines. I am a bit desperate. Anything you can offer would be amazing.

**Comment by fryeguy63** [comment]
I just verified that if I set the connection pool MIN to 0 I get one good query and the rest fail in this context.

**Comment by ben-page** [comment]
I can look into this, but will you please post an example that includes the loop and acquire() call?

**Comment by fryeguy63** [comment]
I updated the post with full code. I am also fully expecting that this code is the problem and not the pool...

**Comment by ben-page** [comment]
I didn't execute the code, but there are few obvious problems.
### Issue 1
If an error happens, connection.release() is not called. The connection will just stay open until it times out and the pool reclaims it.
### Issue 2
It suffers from the closure loop problem. I strongly recommend that you spend some time on this. Understanding scope is vital to successful JavaScript programming. Consider this example:
```javascript
for (var i = 0; i < 3; i++) {
    console.log('in for: ' + i);
    setTimeout(function() {
        console.log('in func: ' + i);
    }, 0);
}
console.log('for complete');
```
```
in for: 0
in for: 1
in for: 2
for complete
in func: 3
in func: 3
in func: 3
```
Inside the for loop, setTimeout queues a function for execution asynchronously. But running code must finish before anything else can execute. So the for loop will complete before any of the queued function are executed. Now, i variable is in the outer scope and can be accessed by all three functions. At the time they execute, i is 3. In your code, something similar is happening with rowCounter.

One solutions is to make a closure. This creates (for each function) a scope and a variable to hold the value of i.

```javascript
function makeClosure(j) {
    return function() {
        console.log('in func: ' + j);
    }
}

for (var i = 0; i < 3; i++) {
    console.log('in for: ' + i);
    setTimeout(makeClosure(i), 0);
}
console.log('for complete');
```
```
in for: 0
in for: 1
in for: 2
for complete
in func: 0
in func: 1
in func: 2
```
  * [asynchronous-process-inside-a-javascript-for-loop](http://stackoverflow.com/questions/11488014/asynchronous-process-inside-a-javascript-for-loop)
  * [javascript-closure-inside-loops-simple-practical-example](http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example)
  * [MDN Closures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures)

### Issue 3
I don't see any reason for the loop. Executing a query multiple times in a loop is red flag. It almost always means your SQL statement needs work. Loop in code is a terribly inefficient way to get databse from a RDBMS.
I suggest that you do a JOIN in your SQL statement all just get all of the values in a single query. Your example would work something like this:
```
SELECT
	StuffStuffNames.Name,
	StuffEmployeeAssignment.EmployeeID,
	StuffEmployeeAssignment.Field1,
	StuffEmployeeAssignment.Field2,
	StuffEmployeeAssignment.Field3 
FROM dbo.StuffStuffNames
INNER JOIN dbo.StuffEmployeeAssignment 
	ON StuffEmployeeAssignment.StuffID = StuffStuffNames.ID
WHERE
	StuffStuffNames.ID = @stuffId
```
### Conculsion
In my opinion, issues 2 and 3 suggests that the original author is not an experienced programmer, especially with JavaScript or SQL. Based solely on this code, I would be very skeptical of anything else he/she wrote.

I'm going to close this because it isn't an issue with the connection pool. But something I said doesn't make sense, please feel free to post again.

**Comment by fryeguy63** [comment]
I really appreciate your thoughtful response. It is awesome that you were willing to take the time to help me knowing that your code was not the issue. For a quick fix I was able to run node in harmony mode and replace the ```var i = 0``` statements with ```let i = 0```. ```let``` was referenced on MDN and by allowing for local block variables the problem went away. I don't like this as a solution to this problem, because it is obvious there is more to "fix", but ```let``` certainly has a place.
